2022-06-12 17:07:57,132 INFO: errors [in /home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/app.py:582]
2022-06-12 17:08:02,918 ERROR: Exception on /venues/3 [GET] [in /home/thegreat/.local/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/app.py", line 204, in show_venue
    return render_template('pages/show_venue.html', venue=data)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 13, in block 'content'
    {% for genre in venue.genres %}
TypeError: 'NoneType' object is not iterable
2022-06-12 17:10:27,054 ERROR: Exception on /venues/2 [GET] [in /home/thegreat/.local/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/app.py", line 204, in show_venue
    return render_template('pages/show_venue.html', venue=data)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 13, in block 'content'
    {% for genre in venue.genres %}
TypeError: 'NoneType' object is not iterable
2022-06-12 17:11:47,711 INFO: errors [in /home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/app.py:582]
2022-06-12 17:11:58,019 ERROR: Exception on /venues/3 [GET] [in /home/thegreat/.local/lib/python3.10/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/app.py", line 204, in show_venue
    return render_template('pages/show_venue.html', venue=data)
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/home/thegreat/.local/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/thegreat/.local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 1, in top-level template code
    {% extends 'layouts/main.html' %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/layouts/main.html", line 103, in top-level template code
    {% block content %}{% endblock %}
  File "/home/thegreat/Documents/GitHub/Project-flyyur/CharlesChilaule/cd0046-SQL-and-Data-Modeling-for-the-Web-master/templates/pages/show_venue.html", line 13, in block 'content'
    {% for genre in venue.genres %}
TypeError: 'NoneType' object is not iterable
